all: analyze

analyze:
	ghdl -a grpPackages/pkgViper/viper-p.vhd
	ghdl -a unitOV2640/OV2640-e.vhd	
	ghdl -a unitOV2640/OV2640-Rtl-a.vhd
	ghdl -a unitVidor/Vidor-e.vhd
	ghdl -a unitVidor/Vidor-Rtl-a.vhd

